name: Test

on:
  - push
  - pull_request

jobs:
  without-gpg:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Run action
        uses: ./
        with:
          directory: ./test/without-gpg/
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}

  with-gpg:
    if: github.repository == 'samuelmeuli/action-maven-publish' # Skip on forks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Install GPG
        if: startsWith(matrix.os, 'macos')
        run: brew install gnupg

      - name: Run action
        uses: ./
        with:
          directory: ./test/with-gpg/
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
